[default_flags]
git = false
ignore = false
venv = true
license = false
readme = false
tests = false
docs = false
docker = false

[preferences]
editor = "vscode"
license = "MIT"
open_editor_on_create = true
